[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[bootstrap.brew.taps]
"controlplane-com/cpln" = "https://github.com/controlplane-com/homebrew-cpln.git"

[bootstrap.packages]
"brew:btop" = "latest"
"brew:gh" = "latest"
"brew:jq" = "latest"
"brew:opa" = "latest"
"brew:podman" = "latest"
"brew:stow" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:ghostty" = "latest"
"pacman:btop" = "latest"
"pacman:jq" = "latest"
"pacman:stow" = "latest"

[tools]
bat = "0.26.1"
fzf = "0.73.1"
go = "1.26.6"
herdr = "0.7.1"
jj = "0.40.0"
neovim = "0.12.5"
node = "26.7.0"
rg = "15.1.0"
starship = "1.26.0"
